#{% set ns = stack_group_config.namespace %}
template:
  path: study-pipeline-infra.j2
stack_name: '{{ ns }}-example-app-1-study-1'
dependencies:
  - develop/glue-job-role.yaml
  - develop/s3-intermediate-bucket.yaml
  - develop/s3-parquet-bucket.yaml
  - develop/namespaced/glue-classifier-array-of-records.yaml
  - develop/namespaced/glue-job-S3ToJsonS3.yaml
parameters:
  Namespace: {{ ns }}
  AppName: example-app-1
  StudyName: study-1
  TemplateBucketName: {{ stack_group_config.artifact_bucket_name }}
  ArtifactRef: {{ stack_group_config.latest_version }}
  JsonBucketName: !stack_output_external bridge-downstream-dev-intermediate-bucket::BucketName
  ParquetBucketName: !stack_output_external bridge-downstream-dev-parquet-bucket::BucketName
  RoleArn: !stack_output_external glue-job-role::RoleArn
  ClassifierName: !stack_output_external '{{ ns }}-array-of-records-classifier::ClassifierName'
  SynapseAuthSsmParameterName: '{{ stack_group_config.synapseAuthSsmParameterName }}'
  S3ToJsonS3JobName: !stack_output_external '{{ ns }}-glue-job-S3ToJsonS3::JobName'
  CastGlueDataTypes: "true"

stack_tags:
  {{ stack_group_config.default_stack_tags }}

sceptre_user_data:
  dataset_crawler_assignments: !file src/glue/resources/dataset_crawler_assignments.yaml
  # this needs to be replaced with real versioned schemas
  dataset_schemas: !file src/glue/resources/table_columns.yaml
