template:
  path: glue-job-S3ToJsonS3.yaml
dependencies:
  - develop/s3-intermediate-bucket.yaml
  - develop/namespaced/invalid-sqs-queue.yaml
  - develop/glue-job-role.yaml
stack_name: '{{ stack_group_config.namespace }}-glue-job-S3ToJsonS3'
parameters:
  JobRole: !stack_output_external glue-job-role::RoleArn
  S3BucketName: !stack_output_external bridge-downstream-dev-intermediate-bucket::BucketName
  BookmarkOption: job-bookmark-disable
  JobDescription: Convert data to JSONS3 data
  MaxConcurrentRuns: '150'
  S3ScriptLocation: s3://{{ stack_group_config.artifact_bucket_name }}/BridgeDownstream/{{ stack_group_config.latest_version }}/glue/jobs/s3_to_json_s3.py
  SynapseAuthSsmParameterName: {{ stack_group_config.synapseAuthSsmParameterName }}
  AdditionalPythonModules: 'synapseclient,jsonschema'
  DatasetMapping: s3://{{ stack_group_config.artifact_bucket_name }}/BridgeDownstream/{{ stack_group_config.namespace }}/glue/resources/dataset_mapping.json
  SchemaMapping: s3://{{ stack_group_config.artifact_bucket_name }}/BridgeDownstream/{{ stack_group_config.namespace }}/glue/resources/schema_mapping.json
  ArchiveMapVersion: v4.7.0
  InvalidSQSQueueUrl: !stack_output_external '{{ stack_group_config.namespace }}-invalid-sqs::PrimaryQueueUrl'
stack_tags:
  {{ stack_group_config.default_stack_tags }}
