FROM python:3.9.10

RUN pip install boto3==1.16.33 pandas==1.1.5 synapseclient==2.5.1 pyarrow==4.0.0
RUN git clone -b etl-129 https://github.com/Sage-Bionetworks/BridgeDownstream.git /root/BridgeDownstream
