template_path: remote/cfn-s3objects-macro.yaml
stack_name: cfn-s3objects-macro
hooks:
  before_launch:
    - !cmd "wget https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/cfn-s3objects-macro/0.0.4/cfn-s3objects-macro.yaml -O templates/remote/cfn-s3objects-macro.yaml"
