template_path: glue-job-role.yaml
stack_name: glue-job-role
parameters:
  SsmParameterName: {{ stack_group_config.synapseAuthSsmParameterName }}
stack_tags:
  {{ stack_group_config.default_stack_tags }}
