#{% set ns = stack_group_config.namespace %}
template_path: s3-bucket.yaml
stack_name: '{{ ns }}-source-bucket'
dependencies:
  - develop/glue-job-role.yaml
parameters:
  BucketName: '{{ ns }}-source'
  ReadOnlyAccessArns:
    - !stack_output_external '{{ ns }}-glue-job-role::RoleArn'
  SynapseIds: '3432808'
stack_tags:
  {{ stack_group_config.default_stack_tags }}
stack_timeout: 10
hooks:
  after_launch:
    - !cmd "python src/scripts/setup_test_data/setup_test_data.py"
